var myName = document.getElementById("name");
var contNum = document.getElementById("cont-num");
var email = document.getElementById("email");
var skil1 = document.getElementById("ski1");
var skil4 = document.getElementById("ski4");
var ski2 = document.getElementById("ski2");
var ski3 = document.getElementById("ski3");
var companyName = document.getElementById("comp-name");
var jobTit = document.getElementById("job-tit");
var jobDes = document.getElementById("job-des");
var startYr = document.getElementById("start-yr");
var endYr = document.getElementById("end-yr");
var workLoc = document.getElementById("work-loc");
var commentsonPre = document.getElementById("pre-comp");
var langOne = document.getElementById("lang-one");
var langTwo = document.getElementById("lang-two");
var achieveemnt1 = document.getElementById("ahieve1");
var achieveemnt2 = document.getElementById("ahieve2");
var achieveemnt3 = document.getElementById("ahieve3");
var achieveemnt4 = document.getElementById("ahieve4");
var eduMatric = document.getElementById("matric");
var interEdu = document.getElementById("inter-edu");
var higherEdu = document.getElementById("higher-ed");
var form = document.getElementById("form");
var btn = document.getElementById("gen-res-btn");
btn === null || btn === void 0 ? void 0 : btn.addEventListener("click", function (e) {
    e.preventDefault();
    localStorage.setItem("name", myName.value);
    localStorage.setItem("contnum", contNum.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("edumatric", eduMatric.value);
    localStorage.setItem("interedu", interEdu.value);
    localStorage.setItem("higeredu", higherEdu.value);
    localStorage.setItem("skil1", skil1.value);
    localStorage.setItem("ski2", ski2.value);
    localStorage.setItem("ski3", ski3.value);
    localStorage.setItem("jobtit", jobTit.value);
    localStorage.setItem("jobdis", jobDes.value);
    localStorage.setItem("startyr", startYr.value);
    localStorage.setItem("compNam", companyName);
    localStorage.setItem("endyr", endYr.value);
    localStorage.setItem("commnets", commentsonPre.value);
    localStorage.setItem("workloc", workLoc.value);
    localStorage.setItem("langone", langOne.value);
    localStorage.setItem("langtwo", langTwo.value);
    localStorage.setItem("achiement", achieveemnt1.value);
    localStorage.setItem("achiement2", achieveemnt2.value);
    localStorage.setItem("achiement3", achieveemnt3.value);
    localStorage.setItem("achiement4", achieveemnt4.value);
    localStorage.setItem("companyNam", companyName.value);
    localStorage.setItem("comments", commentsonPre.value);
    localStorage.setItem("edumatric", eduMatric.value);
    localStorage.setItem("interedu", interEdu.value);
    localStorage.setItem("higherEdu", higherEdu.value);
    localStorage.setItem("ski4", skil4.value);
    console.log(localStorage.getItem("achiement2"));
    console.log(localStorage.getItem("email"));
    window.location.href = "./new.html";
    console.log("script.....");
});
